/**
 * Database types
 * This file will be auto-generated by kysely-codegen after running migrations
 * Run: pnpm db:codegen
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
	? ColumnType<S, I | undefined, U>
	: ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Database {
	users: UsersTable;
	oauth_accounts: OAuthAccountsTable;
	password_accounts: PasswordAccountsTable;
	sessions: SessionsTable;
	novel_templates: NovelTemplatesTable;
	choice_points: ChoicePointsTable;
	user_stories: UserStoriesTable;
	choices: ChoicesTable;
	scenes: ScenesTable;
}

export interface UsersTable {
	id: Generated<string>;
	email: string;
	name: string | null;
	avatar_url: string | null;
	default_preferences: unknown | null; // JSONB
	email_verified: Generated<boolean>;
	created_at: Generated<Timestamp>;
	updated_at: Generated<Timestamp>;
}

export interface OAuthAccountsTable {
	id: Generated<string>;
	user_id: string;
	provider: string;
	provider_user_id: string;
	access_token: string | null;
	refresh_token: string | null;
	expires_at: Timestamp | null;
	created_at: Generated<Timestamp>;
}

export interface PasswordAccountsTable {
	id: Generated<string>;
	user_id: string;
	hashed_password: string;
	created_at: Generated<Timestamp>;
	updated_at: Generated<Timestamp>;
}

export interface SessionsTable {
	id: string;
	user_id: string;
	expires_at: Timestamp;
	created_at: Generated<Timestamp>;
}

export interface NovelTemplatesTable {
	id: Generated<string>;
	title: string;
	description: string;
	base_tropes: string[]; // text[]
	estimated_scenes: number;
	cover_gradient: string;
	created_at: Generated<Timestamp>;
	updated_at: Generated<Timestamp>;
}

export interface ChoicePointsTable {
	id: Generated<string>;
	template_id: string;
	scene_number: number;
	prompt_text: string;
	options: unknown; // JSONB array of choice options
	created_at: Generated<Timestamp>;
}

export interface UserStoriesTable {
	id: Generated<string>;
	user_id: string;
	template_id: string;
	preferences: unknown; // JSONB snapshot of preferences
	current_scene: Generated<number>;
	status: Generated<"in-progress" | "completed">;
	created_at: Generated<Timestamp>;
	updated_at: Generated<Timestamp>;
}

export interface ChoicesTable {
	id: Generated<string>;
	story_id: string;
	choice_point_id: string;
	selected_option: number;
	created_at: Generated<Timestamp>;
}

export interface ScenesTable {
	id: Generated<string>;
	story_id: string;
	scene_number: number;
	content: string;
	word_count: number;
	created_at: Generated<Timestamp>;
}
